import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CardRecipe from '../components/Cardrecipe'
import CardCollection from '../components/CardCollection'

export default function Home() {
    const recipe = {
        title: "Udang Goreng Tepung Saus Asam Manis",
        level: "Mudah",
        time: 30,
        rating: 4.5,
        category: "Makanan",
        creator: "Inem Susanti",
        image: "https://www.sidechef.com/recipe/c8738a39-6d2b-4905-a8b7-ad0f0c80311b.jpg",
    }
    const recipe1 = {
        title: "Udang Goreng",
        level: "Mudah",
        time: 30,
        rating: 4.5,
        category: "Makanan",
        creator: "Inem Susanti",
        image: "https://www.sidechef.com/recipe/c8738a39-6d2b-4905-a8b7-ad0f0c80311b.jpg",
    }

    const collection = {
        title: "Inspirasi kreasi resep kayu manis wuenak tenan ra ngapusi",
        images: ["https://www.sidechef.com/recipe/c8738a39-6d2b-4905-a8b7-ad0f0c80311b.jpg", "https://www.sidechef.com/recipe/c8738a39-6d2b-4905-a8b7-ad0f0c80311b.jpg", "https://www.sidechef.com/recipe/c8738a39-6d2b-4905-a8b7-ad0f0c80311b.jpg"],
        categories: [{
            name: "Makanan",
            count: 2,
        },
        {
            name: "Cemilan",
            count: 2,
        },
        {
            name: "Minuman",
            count: 2,
        }
        ],
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <CardCollection collection={collection} />
                <div className="grid gap-8 grid-cols-2">
                    <CardRecipe recipe={recipe} />
                    <CardRecipe recipe={recipe1} />
                </div>

            </main>
        </div>
    )
}
